export const SUCURSALES = [
    "ACTOPAN", "AMOZOC", "APIZACO", "ATITALAQUIA", "ATLACOMULCO",
    "CANCUN 1", "CANCUN 2", "CEIBA", "CELAYA", "CHOLULA",
    "CUAUTLA", "GUADALAJARA", "HUEJUTLA", "IRAPUATO", "IXMIQUILPAN",
    "MERIDA", "MIXQUIAHUALA", "MORELIA", "OAXACA 1", "OAXACA 2",
    "PACHUCA 1", "PACHUCA 2", "PLAYA DEL CARMEN", "PUEBLA 1", "PUEBLA 2",
    "PUEBLA 3", "QUERETARO 1", "QUERETARO 2", "QUERETARO 3", "TEHUACAN",
    "TEZIUTLAN", "TIZAYUCA", "TULANCINGO 1", "TULANCINGO 2", "VERACRUZ",
    "VILLAHERMOSA", "ZUMPANGO 1", "ZUMPANGO 2"
];

export const SUCURSAL_ACRONYMS: Record<string, string> = {
    "AMOZOC": "AMO",
    "APIZACO": "APZ",
    "ATITALAQUIA": "ATI",
    "ATLACOMULCO": "ATL",
    "ACTOPAN": "ACT",
    "CANCUN 1": "CAN1",
    "CANCUN 2": "CAN2",
    "CEIBA": "CEI",
    "CELAYA": "CEL",
    "CHOLULA": "CHO",
    "CUAUTLA": "CUA",
    "GUADALAJARA": "GDL",
    "HUEJUTLA": "HUE",
    "IRAPUATO": "IRA",
    "IXMIQUILPAN": "IXM",
    "MERIDA": "MER",
    "MORELIA": "MOR",
    "MIXQUIAHUALA": "MIX",
    "OAXACA 1": "OAX1",
    "OAXACA 2": "OAX2",
    "PACHUCA 1": "PAC1",
    "PACHUCA 2": "PAC2",
    "PLAYA DEL CARMEN": "PDC",
    "PUEBLA 1": "PUE1",
    "PUEBLA 2": "PUE2",
    "PUEBLA 3": "PUE3",
    "QUERETARO 1": "QR01",
    "QUERETARO 2": "QR02",
    "QUERETARO 3": "QR03",
    "TEHUACAN": "TEH",
    "TEZIUTLAN": "TEZ",
    "TIZAYUCA": "TIZ",
    "TULANCINGO 1": "TUL1",
    "TULANCINGO 2": "TUL2",
    "VERACRUZ": "VER",
    "VILLAHERMOSA": "VHM",
    "ZUMPANGO 1": "ZUM1",
    "ZUMPANGO 2": "ZUM2"
};

export const PRODUCT_CATEGORIES = [
    { id: "aro-amb", name: "Aromatizante Ambiental", image: "https://i.imgur.com/86dsPZV.jpeg" },
    { id: "antibac", name: "Antibacteriales", image: "https://i.imgur.com/RQfPreB.png" },
    { id: "bs-aro-amb", name: "Bases aromatizante ambiental", image: "https://i.imgur.com/lPo1L37.jpeg" },
    { id: "bs-lim-mult", name: "Bases limpiadores liquidos multiusos", image: "https://i.imgur.com/T99Fqdz.jpeg" },
    { id: "crem-corp", name: "Crema corporal", image: "https://i.imgur.com/NdvM2Zf.png" },
    { id: "det-trastes", name: "Detergente liquido para trastes", image: "https://i.imgur.com/gBct0aj.jpeg" },
    { id: "det-ropa", name: "Detergente líquido para ropa", image: "https://i.imgur.com/58v54Q6.jpeg" },
    { id: "enj-cap", name: "Enjuagues capilares", image: "https://i.imgur.com/EE3YF65.jpeg" },
    { id: "esp-hogar", name: "Especialidades cuidado del hogar", image: "https://i.imgur.com/RqcQxOB.jpeg" },
    { id: "esp-lavand", name: "Especialidades lavanderia", image: "https://i.imgur.com/ak01Ugq.png" },
    { id: "jab-manos", name: "Jabón liquido para manos", image: "https://i.imgur.com/WWHmKQ4.jpeg" },
    { id: "automotriz", name: "Línea automotriz", image: "https://i.imgur.com/zWXi9RD.png" },
    { id: "lim-mult", name: "Limpiador liquido multiusos", image: "https://i.imgur.com/f5SwpJ6.jpeg" },
    { id: "prod-interm", name: "Producto intermedio", image: "https://i.imgur.com/KjckUNn.jpeg" },
    { id: "refaro", name: "Reforzador de aromas(REFARO)", image: "https://i.imgur.com/MIJLRTO.png" },
    { id: "shampoo", name: "Shampoo capilar", image: "https://i.imgur.com/NdvM2Zf.png" }, // Reusing crema as placeholder if needed
    { id: "suavizante", name: "Suavizante de telas", image: "https://i.imgur.com/EE3YF65.jpeg" },
    { id: "especial", name: "Producto terminado especial", image: "https://i.imgur.com/epnUSfo.jpeg" },
    { id: "disoluciones", name: "Disoluciones intermedias", image: "https://i.imgur.com/RqcQxOB.jpeg" }
];

export const CATEGORY_PRODUCTS: Record<string, string[]> = {
    "Aromatizante Ambiental": ["AROANII", "AROCAN", "AROCAR", "AROCHIC", "AROCHIF", "ARODRA", "AROEST", "AROETE", "AROFER", "AROGAR", "AROHUG", "AROLUX", "ARONOR", "AROPOL"],
    "Antibacteriales": ["GELANT", "JABMAK", "LIMSAK", "SANBAK", "TRAGRA"],
    "Bases aromatizante ambiental": ["BAROANII", "BAROCAN", "BAROCAR", "BAROCHIC", "BAROCHIF", "BARODRA", "BAROEST", "BAROETE", "BAROFER", "BAROGAR", "BAROHUG", "BAROLUX", "BARONOR", "BAROPOL", "BAROMANC"],
    "Bases limpiadores liquidos multiusos": ["BLIMALA", "BLIMANI", "BLIMBAB", "BLIMBOS", "BLIMBRI", "BLIMCAN", "BLIMCAR", "BLIMCAS", "BLIMCER", "BLIMCHI", "BLIMCHIC", "BLIMCOC", "BLIMDRAG", "BLIMEST", "BLIMETE", "BLIMFER", "BLIMFLO", "BLIMFRU", "BLIMGAR", "BLIMGPO", "BLIMHUG", "BLIMLAV", "BLIMLIM", "BLIMLIS", "BLIMLUX", "BLIMMAN", "BLIMMAND", "BLIMMANC", "BLIMMAR-1", "BLIMMAR-2", "BLIMMEN", "BLIMNAR", "BLIMNOR", "BLIMPER", "BLIMPOL", "BLIMPRI", "BLIMSTE", "BLIMVIO", "BPINBLA", "BPINCRI", "BPINVER"],
    "Crema corporal": ["CREBAB", "CREDEL", "CRELIM", "CREMIE", "CREROS", "CRESAB", "CREWHI"],
    "Detergente liquido para trastes": ["TRABLUE", "TRALIM", "TRAMAN", "TRANAR", "TRATOR", "XPUMAX"],
    "Detergente líquido para ropa": ["AQUA", "COLBLA", "COLGIN", "COLNEG", "DETDON", "ENCANTO", "GIRIEL", "GIRIEL2", "GIRIELOXI", "GIRDOW", "PERGIN", "PERLA", "SHAGIN", "SUNSET", "VELGIN", "VIVGIN", "ZOTAZU", "ZOTBLA", "ZOTROS"],
    "Enjuagues capilares": ["ENJROS", "ENJDUR", "ENJHIE"],
    "Especialidades cuidado del hogar": ["ACEROJ", "CLO", "CLOGEL", "DETAMO", "DETER", "INS", "LIMREP", "LIMVID", "MOP", "QUILIQ", "QUIPAS", "QUISAR", "SARRIGEL", "SHAMAS", "TEFESP", "TEFLIQ", "DESBRA"],
    "Especialidades lavanderia": ["DESMUG", "DETNEU", "DETPIN", "GINESH", "PLAPLUS", "PLAFAC"],
    "Jabón liquido para manos": ["JABCER", "JABCOC", "JABDUR", "JABHIE", "JABNEU", "JABPM", "JABPRI", "JABUVA"],
    "Línea automotriz": ["ALTBRI", "BRIGEL", "BRILIQ", "CERLIQ", "CREMEC", "DESIND", "DESMOT", "GINESP", "GINLIQ", "SHACER", "SHACLA"],
    "Limpiador liquido multiusos": ["LIMALA", "LIMBOS", "LIMBRI", "LIMCAN", "LIMCAS", "LIMCHI", "LIMFRU", "LIMLAV", "LIMLIM", "LIMLIS", "LIMMANC", "LIMMAND", "LIMMAR", "LIMMEN", "LIMPERM", "LIMPOET", "LIMPRI", "LIMSTE", "LIMVIO", "PINBLA", "PINO", "PINVER"],
    "Producto intermedio": ["DETALC", "EMU", "FFLO", "BSUA"],
    "Reforzador de aromas(REFARO)": ["REFARO-SUE", "REFARO-LIB", "REFARO-MAG", "REFARO-INT", "REFARO-NAT", "REFARO-LUN", "REFARO-BLUE", "REFARO-EDE", "REFARO-PAS", "REFARO-SEN", "REFARO-PRI", "REFARO-BAB", "REFARO-DEL"],
    "Shampoo capilar": ["SHAPAN", "SHAHEA", "SHADUR", "SHAPLU", "SHAHIE"],
    "Suavizante de telas": ["SUASUE", "SUALIB", "SUAMAG", "SUAINT", "SUANAT", "SUALUN", "SUABLU", "SUAPAS", "SUASEN", "SUAPRI", "SUABAB", "SUADEL", "SUANEU"],
    "Producto terminado especial": [],
    "Disoluciones intermedias": ["CITGIN", "NAOH10", "ESPSNT25"]
};

export const PRODUCT_STANDARDS: Record<string, { min?: number, max?: number }> = {
    "LIMLIM": { min: 1.4, max: 1.6 },
    "LIMVIO": { min: 1.3, max: 1.4 },
    "LIMMAR": { min: 1.1, max: 1.7 },
    "LIMCAS": { min: 1.6, max: 1.7 },
    "LIMBRI": { min: 1.6, max: 1.7 },
    "LIMCAN": { min: 1.9, max: 2.0 },
    "LIMCHI": { min: 1.6, max: 1.9 },
    "LIMBOS": { min: 1.6, max: 1.8 },
    "LIMLAV": { min: 1.0, max: 1.2 },
    "LIMPERM": { min: 1.6, max: 1.7 },
    "LIMMEN": { min: 1.2, max: 1.5 },
    "LIMSTE": { min: 1.5, max: 1.7 },
    "LIMFRU": { min: 1.2, max: 1.5 },
    "LIMPOET": { min: 1.6, max: 1.8 },
    "LIMMANC": { min: 1.9, max: 2.1 },
    "LIMLIS": { min: 1.1, max: 1.3 },
    "LIMALA": { min: 1.6, max: 1.8 },
    "TRALIM": { min: 16.5, max: 17.5 },
    "TRAMAN": { min: 15.5, max: 17.5 },
    "TRANAR": { min: 16.1, max: 17.5 },
    "TRATOR": { min: 14.5, max: 17.0 },
    "XPUMAX": { min: 15.6, max: 17.5 },
    "CLOGEL": { min: 6.2, max: 8.0 },
    "CLO": { min: 6.0, max: 8.0 },
    "PINO": { min: 3.6, max: 4.2 },
    "QUIPAS": { min: 27.5, max: 29.1 },
    "DETNEU": { min: 11.0, max: 12.1 },
    "INS": { min: 1.5, max: 2.0 },
    "DETER": { min: 16.0, max: 17.9 },
    "LIMVID": { min: 1.2, max: 1.3 },
    "DETAMO": { min: 13.0, max: 13.9 },
    "DESIND": { min: 23.5, max: 25.7 },
    "TEFLIQ": { min: 10.4, max: 11.3 },
    "TESESP": { min: 17.0, max: 19.3 },
    "SHAMAS": { min: 8.0, max: 9.7 },
    "DESBRA": { min: 8.0, max: 9.7 },
    "COLGIN": { min: 9.0, max: 10.5 },
    "COLBLA": { min: 9.1, max: 10.5 },
    "COLNEG": { min: 9.2, max: 10.5 },
    "GIRIEL": { min: 9.0, max: 10.5 },
    "GIRIEL2": { min: 9.0, max: 10.5 },
    "PERGIN": { min: 9.0, max: 10.5 },
    "VIVGIN": { min: 8.5, max: 10.5 },
    "GIRIELOXI": { min: 8.5, max: 10.5 },
    "SUNSET": { min: 8.5, max: 10.5 },
    "SHAGIN": { min: 8.6, max: 10.5 },
    "ZOTROS": { min: 10.0, max: 14.5 },
    "ZOTBLA": { min: 10.0, max: 14.5 },
    "ZOTAZU": { min: 10.0, max: 14.5 },
    "AQUA": { min: 10.5, max: 12.5 },
    "DETDON": { min: 11.5, max: 13.5 },
    "PERLA": { min: 11.1, max: 13.5 },
    "ENCANTO": { min: 11.0, max: 13.5 },
    "VELGIN": { min: 8.3, max: 10.8 },
    "SUASUE": { min: 1.3, max: 2.0 },
    "SUALIB": { min: 1.5, max: 2.2 },
    "SUAMAG": { min: 1.4, max: 2.6 },
    "SUAINT": { min: 1.7, max: 2.4 },
    "SUANAT": { min: 1.5, max: 2.1 },
    "SUALUN": { min: 1.9, max: 2.5 },
    "SUABLU": { min: 1.7, max: 2.1 },
    "SUAPAS": { min: 1.2, max: 1.9 },
    "SUASEN": { min: 1.8, max: 2.3 },
    "SUAPRI": { min: 1.8, max: 2.3 },
    "SUABAB": { min: 1.3, max: 2.0 },
    "SUADEL": { min: 1.3, max: 2.0 },
    "DESMUG": { min: 14.5, max: 16.5 },
    "DETPIN": { min: 8.9, max: 9.6 },
    "GINESH": { min: 5.2, max: 5.9 },
    "SHACER": { min: 8.5, max: 9.5 },
    "SHACLA": { min: 12.0, max: 13.5 },
    "ALTBRI": { min: 38.0, max: 38.6 },
    "BRILIQ": { min: 18.5, max: 20.5 },
    "BRIGEL": { min: 21.5, max: 24.5 },
    "GINLIQ": { min: 10.5, max: 11.0 },
    "GINESP": { min: 17.0, max: 19.5 },
    "DESMOT": { min: 21.2, max: 23.2 },
    "CERLIQ": { min: 7.5, max: 8.9 },
    "CREMEC": { min: 37.0, max: 40.5 },
    "GELANT": { min: 21.6, max: 23.2 },
    "SANBAK": { min: 1.0, max: 1.3 },
    "LIMSAK": { min: 1.6, max: 2.0 },
    "JABMAK": { min: 12.0, max: 13.5 },
    "TRAGRA": { min: 20.0, max: 22.0 },
    "JABPM": { min: 10.5, max: 14.0 },
    "JABNEU": { min: 10.5, max: 14.0 },
    "JABCER": { min: 12.0, max: 14.0 },
    "JABUVA": { min: 13.0, max: 14.5 },
    "JABHIE": { min: 10.5, max: 12.5 },
    "JABCOC": { min: 10.0, max: 11.5 },
    "SHAPAN": { min: 7.5, max: 9.5 },
    "SHAHEA": { min: 7.5, max: 9.5 },
    "ENJROS": { min: 1.5, max: 2.5 },
    "CREDEL": { min: 18.0, max: 22.0 },
    "DETALC": { min: 15.5, max: 17.5 },
    "CITGIN": { min: 20.0, max: 25.0 },
    "NAOH10": { min: 8.0, max: 12.0 },
    "ESPSNT25": { min: 25.0, max: 30.0 }
};

export const PH_STANDARDS: Record<string, { min: number, max: number }> = {
    "TRALIM": { min: 7, max: 9 }, "TRAMAN": { min: 7, max: 9 }, "TRANAR": { min: 7, max: 9 }, "TRATOR": { min: 7, max: 9 }, "XPUMAX": { min: 7, max: 9 },
    "CLOGEL": { min: 7, max: 9 }, "QUIPAS": { min: 7, max: 9 }, "DETNEU": { min: 7, max: 8 }, "DETAMO": { min: 7, max: 9 }, "DESBRA": { min: 7, max: 9 },
    "TESESP": { min: 7, max: 8 }, "SHAMAS": { min: 7, max: 8 },
    "COLGIN": { min: 7, max: 9 }, "COLBLA": { min: 7, max: 9 }, "COLNEG": { min: 7, max: 9 }, "GIRIEL": { min: 7, max: 9 }, "GIRIEL2": { min: 7, max: 9 },
    "PERGIN": { min: 7, max: 9 }, "VIVGIN": { min: 7, max: 9 }, "GIRIELOXI": { min: 7, max: 9 }, "SUNSET": { min: 7, max: 9 }, "SHAGIN": { min: 7, max: 9 },
    "ZOTROS": { min: 7, max: 9 }, "ZOTBLA": { min: 7, max: 9 }, "ZOTAZU": { min: 7, max: 9 }, "AQUA": { min: 7, max: 9 }, "DETDON": { min: 7, max: 9 },
    "PERLA": { min: 7, max: 9 }, "ENCANTO": { min: 7, max: 9 }, "VELGIN": { min: 7, max: 9 },
    "DESMUG": { min: 8, max: 10 }, "DETPIN": { min: 7, max: 9 }, "GINESH": { min: 3, max: 4 },
    "SHACER": { min: 6, max: 7 }, "SHACLA": { min: 6, max: 7 }, "BRIGEL": { min: 6, max: 7 }, "GINESP": { min: 6, max: 7 },
    "GELANT": { min: 6, max: 7 }, "JABMAK": { min: 6, max: 7 }, "TRAGRA": { min: 7, max: 9 },
    "JABPM": { min: 5, max: 6 }, "JABNEU": { min: 5, max: 6 }, "JABCER": { min: 5, max: 6 }, "JABUVA": { min: 5, max: 6 }, "JABHIE": { min: 5, max: 6 }, "JABCOC": { min: 5, max: 6 },
    "SHAPAN": { min: 6, max: 7 }, "SHAHEA": { min: 6, max: 7 }, "CREDEL": { min: 6, max: 7 },
    "DETALC": { min: 9, max: 11 },
};

export const APPEARANCE_STANDARDS: Record<string, string> = {
    "ACEROJ": "CRISTALINO", "ALTBRI": "CRISTALINO", "AQUA": "CRISTALINO", "AROANII": "OPACO", "AROCAN": "OPACO", "AROCAR": "OPACO", "AROCHIC": "OPACO", "AROCHIF": "OPACO", "ARODRA": "OPACO", "AROEST": "OPACO", "AROETE": "OPACO", "AROFER": "OPACO", "AROGAR": "OPACO", "AROHUG": "OPACO", "AROLUX": "OPACO", "ARONOR": "OPACO", "AROPOL": "OPACO", "BAROANII": "OPACO", "BAROCAN": "OPACO", "BAROCAR": "OPACO", "BAROCHIC": "OPACO", "BAROCHIF": "OPACO", "BARODRA": "OPACO", "BAROEST": "OPACO", "BAROETE": "OPACO", "BAROFER": "OPACO", "BAROGAR": "OPACO", "BAROHUG": "OPACO", "BAROLUX": "OPACO", "BAROMANC": "OPACO", "BARONOR": "OPACO", "BAROPOL": "OPACO", "BLIMALA": "OPACO", "BLIMANI": "OPACO", "BLIMBAB": "OPACO", "BLIMBOS": "OPACO", "BLIMBRI": "OPACO", "BLIMCAN": "OPACO", "BLIMCAR": "OPACO", "BLIMCAS": "OPACO", "BLIMCER": "OPACO", "BLIMCHI": "OPACO", "BLIMCHIC": "OPACO", "BLIMCOC": "OPACO", "BLIMDRAG": "OPACO", "BLIMEST": "OPACO", "BLIMETE": "OPACO", "BLIMFER": "OPACO", "BLIMFLO": "OPACO", "BLIMFRU": "OPACO", "BLIMGAR": "OPACO", "BLIMGPO": "OPACO", "BLIMHUG": "OPACO", "BLIMLAV": "OPACO", "BLIMLIM": "OPACO", "BLIMLIS": "OPACO", "BLIMLUX": "OPACO", "BLIMMAN": "OPACO", "BLIMMAND": "OPACO", "BLIMMANC": "OPACO", "BLIMMAR-1": "OPACO", "BLIMMAR-2": "OPACO", "BLIMMEN": "OPACO", "BLIMNAR": "OPACO", "BLIMNOR": "OPACO", "BLIMPER": "OPACO", "BLIMPOL": "OPACO", "BLIMPRI": "OPACO", "BLIMSTE": "OPACO", "BLIMVIO": "OPACO", "BPINBLA": "OPACO", "BPINCRI": "OPACO", "BPINVER": "OPACO", "BRIGEL": "CRISTALINO", "BRILIQ": "CRISTALINO", "BSUA": "CRISTALINO", "CERLIQ": "CRISTALINO", "CITGIN": "CRISTALINO", "CLO": "CRISTALINO", "CLOGEL": "CRISTALINO", "COLBLA": "CRISTALINO", "COLGIN": "CRISTALINO", "COLNEG": "CRISTALINO", "CREBAB": "APERLADO", "CREDEL": "APERLADO", "CRELIM": "APERLADO", "CREMEC": "CRISTALINO", "CREMIE": "APERLADO", "CREROS": "APERLADO", "CRESAB": "APERLADO", "CREWHI": "APERLADO", "DES": "CRISTALINO", "DESIND": "CRISTALINO", "DETDON": "CRISTALINO", "DETNEU": "CRISTALINO", "DETPIN": "CRISTALINO", "DETER": "CRISTALINO", "DETALC": "CRISTALINO", "DETAMO": "CRISTALINO", "EMU": "CRISTALINO", "ENCANTO": "CRISTALINO", "ENJDUR": "CRISTALINO", "ENJHIE": "CRISTALINO", "ENJROS": "CRISTALINO", "ESPSNT25": "CRISTALINO", "FFLO": "CRISTALINO", "GELANT": "CRISTALINO", "GINESH": "CRISTALINO", "GINESP": "CRISTALINO", "GINLIQ": "CRISTALINO", "GIRIEL": "CRISTALINO", "GIRIEL2": "CRISTALINO", "GIRIELOXI": "CRISTALINO", "INS": "CRISTALINO", "JABCER": "CRISTALINO", "JABCOC": "CRISTALINO", "JABDUR": "CRISTALINO", "JABHIE": "CRISTALINO", "JABMAK": "CRISTALINO", "JABNEU": "CRISTALINO", "JABPM": "CRISTALINO", "JABUVA": "CRISTALINO", "LIMALA": "CRISTALINO", "LIMBOS": "CRISTALINO", "LIMBRI": "CRISTALINO", "LIMCAN": "CRISTALINO", "LIMCAS": "CRISTALINO", "LIMCHI": "CRISTALINO", "LIMLAV": "CRISTALINO", "LIMLIM": "CRISTALINO", "LIMLIS": "CRISTALINO", "LIMMAR": "CRISTALINO", "LIMMEN": "CRISTALINO", "LIMPERM": "CRISTALINO", "LIMPOET": "CRISTALINO", "LIMREP": "CRISTALINO", "LIMSAK": "CRISTALINO", "LIMSTE": "CRISTALINO", "LIMVID": "CRISTALINO", "LIMVIO": "CRISTALINO", "MOP": "CRISTALINO", "NAOH10": "CRISTALINO", "PINO": "CRISTALINO", "PINBLA": "CRISTALINO", "PINVER": "CRISTALINO", "PLAFAC": "CRISTALINO", "PLAPLUS": "CRISTALINO", "QUILIQ": "CRISTALINO", "QUIPAS": "CRISTALINO", "QUISAR": "CRISTALINO", "SARRIGEL": "CRISTALINO", "SANBAK": "CRISTALINO", "SHACER": "CRISTALINO", "SHACLA": "CRISTALINO", "SHADUR": "CRISTALINO", "SHAHEA": "CRISTALINO", "SHAHIE": "CRISTALINO", "SHAMAS": "CRISTALINO", "SHAPAN": "CRISTALINO", "SHAPLU": "CRISTALINO", "SHAGIN": "CRISTALINO", "SUABAB": "OPACO", "SUABLU": "OPACO", "SUADEL": "OPACO", "SUAINT": "OPACO", "SUALIB": "OPACO", "SUALUN": "OPACO", "SUAMAG": "OPACO", "SUANAT": "OPACO", "SUANEU": "OPACO", "SUAPAS": "OPACO", "SUAPRI": "OPACO", "SUASEN": "OPACO", "SUASUE": "OPACO", "SUNSET": "CRISTALINO", "TEFLIQ": "CRISTALINO", "TESESP": "CRISTALINO", "TRABLU": "CRISTALINO", "TRAGRA": "CRISTALINO", "TRALIM": "CRISTALINO", "TRAMAN": "CRISTALINO", "TRANAR": "CRISTALINO", "TRATOR": "CRISTALINO", "VELGIN": "CRISTALINO", "VIVGIN": "CRISTALINO", "XPUMAX": "CRISTALINO", "ZOTAZU": "CRISTALINO", "ZOTBLA": "CRISTALINO", "ZOTROS": "OPACO"
};

export const PARAMETER_APPLICABILITY: Record<string, { solidos: boolean, ph: boolean }> = {
    "AROANII": { solidos: false, ph: false }, "AROCAN": { solidos: false, ph: false }, "AROCAR": { solidos: false, ph: false }, "AROCHIC": { solidos: false, ph: false }, "AROCHIF": { solidos: false, ph: false }, "ARODRA": { solidos: false, ph: false }, "AROEST": { solidos: false, ph: false }, "AROETE": { solidos: false, ph: false }, "AROFER": { solidos: false, ph: false }, "AROGAR": { solidos: false, ph: false }, "AROHUG": { solidos: false, ph: false }, "AROLUX": { solidos: false, ph: false }, "ARONOR": { solidos: false, ph: false }, "AROPOL": { solidos: false, ph: false },
    "BAROANII": { solidos: false, ph: false }, "BAROCAN": { solidos: false, ph: false }, "BAROCAR": { solidos: false, ph: false }, "BAROCHIC": { solidos: false, ph: false }, "BAROCHIF": { solidos: false, ph: false }, "BARODRA": { solidos: false, ph: false }, "BAROEST": { solidos: false, ph: false }, "BAROETE": { solidos: false, ph: false }, "BAROFER": { solidos: false, ph: false }, "BAROGAR": { solidos: false, ph: false }, "BAROHUG": { solidos: false, ph: false }, "BAROLUX": { solidos: false, ph: false }, "BARONOR": { solidos: false, ph: false }, "BAROPOL": { solidos: false, ph: false }, "BAROMANC": { solidos: false, ph: false },
    "LIMLIM": { solidos: true, ph: false }, "LIMVIO": { solidos: true, ph: false }, "LIMMAR": { solidos: true, ph: false }, "LIMCAS": { solidos: true, ph: false }, "LIMBRI": { solidos: true, ph: false }, "LIMCAN": { solidos: true, ph: false }, "LIMCHI": { solidos: true, ph: false }, "LIMBOS": { solidos: true, ph: false }, "LIMLAV": { solidos: true, ph: false }, "LIMPERM": { solidos: true, ph: false }, "LIMMEN": { solidos: true, ph: false }, "LIMSTE": { solidos: true, ph: false }, "LIMFRU": { solidos: true, ph: false }, "LIMPOET": { solidos: true, ph: false }, "LIMMANC": { solidos: true, ph: false }, "LIMLIS": { solidos: true, ph: false }, "LIMALA": { solidos: true, ph: false }, "PINO": { solidos: true, ph: false }, "PINBLA": { solidos: false, ph: false }, "PINVER": { solidos: false, ph: false },
    "TRALIM": { solidos: true, ph: true }, "TRAMAN": { solidos: true, ph: true }, "TRANAR": { solidos: true, ph: true }, "TRATOR": { solidos: true, ph: true }, "TRABLU": { solidos: true, ph: true }, "XPUMAX": { solidos: true, ph: true },
    "CLOGEL": { solidos: true, ph: true }, "CLO": { solidos: true, ph: false }, "QUIPAS": { solidos: false, ph: false }, "DETNEU": { solidos: true, ph: true }, "INS": { solidos: true, ph: false }, "DETER": { solidos: true, ph: true }, "LIMVID": { solidos: true, ph: false }, "DETAMO": { solidos: true, ph: true }, "TEFLIQ": { solidos: true, ph: false }, "TESESP": { solidos: true, ph: true }, "SHAMAS": { solidos: true, ph: true }, "ACEROJ": { solidos: false, ph: false }, "LIMREP": { solidos: true, ph: false }, "MOP": { solidos: false, ph: false }, "QUILIQ": { solidos: false, ph: false }, "QUISAR": { solidos: false, ph: false }, "SARRIGEL": { solidos: false, ph: false },
    "COLGIN": { solidos: true, ph: true }, "COLBLA": { solidos: true, ph: true }, "COLNEG": { solidos: true, ph: true }, "GIRIEL": { solidos: true, ph: true }, "GIRIEL2": { solidos: true, ph: true }, "PERGIN": { solidos: true, ph: true }, "VIVGIN": { solidos: true, ph: true }, "GIRIELOXI": { solidos: true, ph: true }, "SUNSET": { solidos: true, ph: true }, "SHAGIN": { solidos: true, ph: true }, "ZOTROS": { solidos: true, ph: true }, "ZOTBLA": { solidos: true, ph: true }, "ZOTAZU": { solidos: true, ph: true }, "AQUA": { solidos: true, ph: true }, "DETDON": { solidos: true, ph: true }, "PERLA": { solidos: true, ph: true }, "ENCANTO": { solidos: true, ph: true }, "VELGIN": { solidos: true, ph: true },
    "SUASUE": { solidos: true, ph: false }, "SUALIB": { solidos: true, ph: false }, "SUAMAG": { solidos: true, ph: false }, "SUAINT": { solidos: true, ph: false }, "SUANAT": { solidos: true, ph: false }, "SUALUN": { solidos: true, ph: false }, "SUABLU": { solidos: true, ph: false }, "SUAPAS": { solidos: true, ph: false }, "SUASEN": { solidos: true, ph: false }, "SUAPRI": { solidos: true, ph: false }, "SUABAB": { solidos: true, ph: false }, "SUADEL": { solidos: true, ph: false }, "SUANE": { solidos: true, ph: false },
    "DESMUG": { solidos: true, ph: true }, "DETPIN": { solidos: true, ph: true }, "GINESH": { solidos: true, ph: true }, "PLAFAC": { solidos: false, ph: false }, "PLAPLUS": { solidos: false, ph: false },
    "SHACER": { solidos: true, ph: true }, "SHACLA": { solidos: true, ph: true }, "ALTBRI": { solidos: true, ph: false }, "BRILIQ": { solidos: true, ph: false }, "BRIGEL": { solidos: true, ph: true }, "GINLIQ": { solidos: true, ph: false }, "GINESP": { solidos: true, ph: true }, "DESMOT": { solidos: true, ph: false }, "CERLIQ": { solidos: true, ph: false }, "CREMEC": { solidos: true, ph: false }, "DESIND": { solidos: true, ph: false },
    "GELANT": { solidos: true, ph: true }, "SANBAK": { solidos: true, ph: false }, "LIMSAK": { solidos: true, ph: false }, "JABMAK": { solidos: true, ph: true }, "TRAGRA": { solidos: true, ph: true },
    "JABPM": { solidos: true, ph: true }, "JABNEU": { solidos: true, ph: true }, "JABCER": { solidos: true, ph: true }, "JABUVA": { solidos: true, ph: true }, "JABHIE": { solidos: true, ph: true }, "JABCOC": { solidos: true, ph: true }, "JABDUR": { solidos: true, ph: true },
    "SHAPAN": { solidos: true, ph: true }, "SHAHEA": { solidos: true, ph: true }, "SHADUR": { solidos: true, ph: true }, "SHAPLU": { solidos: true, ph: true }, "SHAHIE": { solidos: true, ph: true },
    "ENJROS": { solidos: true, ph: false }, "ENJDUR": { solidos: true, ph: false }, "ENJHIE": { solidos: true, ph: false },
    "CREDEL": { solidos: true, ph: true }, "CREBAB": { solidos: true, ph: true }, "CRELIM": { solidos: true, ph: true }, "CREMIE": { solidos: true, ph: true }, "CREROS": { solidos: true, ph: true }, "CRESAB": { solidos: true, ph: true }, "CREWHI": { solidos: true, ph: true },
    "REFARO-SUE": { solidos: false, ph: false }, "REFARO-LIB": { solidos: false, ph: false }, "REFARO-MAG": { solidos: false, ph: false }, "REFARO-INT": { solidos: false, ph: false }, "REFARO-NAT": { solidos: false, ph: false }, "REFARO-LUN": { solidos: false, ph: false }, "REFARO-BLUE": { solidos: false, ph: false }, "REFARO-EDE": { solidos: false, ph: false }, "REFARO-PAS": { solidos: false, ph: false }, "REFARO-SEN": { solidos: false, ph: false }, "REFARO-PRI": { solidos: false, ph: false }, "REFARO-BAB": { solidos: false, ph: false }, "REFARO-DEL": { solidos: false, ph: false },
    "DETALC": { solidos: true, ph: true }, "EMU": { solidos: false, ph: false }, "FFLO": { solidos: false, ph: false }, "BSUA": { solidos: false, ph: false },
    "CITGIN": { solidos: true, ph: false }, "NAOH10": { solidos: true, ph: false }, "ESPSNT25": { solidos: true, ph: false }
};
