export const SUCURSALES = [
    "ACTOPAN", "AMOZOC", "APIZACO", "ATITALAQUIA", "ATLACOMULCO",
    "CANCUN 1", "CANCUN 2", "CEIBA", "CELAYA", "CHOLULA",
    "CUAUTLA", "GUADALAJARA", "HUEJUTLA", "IRAPUATO", "IXMIQUILPAN",
    "MERIDA", "MIXQUIAHUALA", "MORELIA", "OAXACA 1", "OAXACA 2",
    "PACHUCA 1", "PACHUCA 2", "PLAYA DEL CARMEN", "PUEBLA 1", "PUEBLA 2",
    "PUEBLA 3", "PUEBLA 4", "QUERETARO 1", "QUERETARO 2", "QUERETARO 3", "TEHUACAN",
    "TEZIUTLAN", "TIZAYUCA", "TULANCINGO 1", "TULANCINGO 2", "VERACRUZ",
    "VILLAHERMOSA", "ZUMPANGO 1", "ZUMPANGO 2",
    "CEDIS", "CORPORATIVO"
];

export const SUCURSAL_ACRONYMS: Record<string, string> = {
    "AMOZOC": "AMO",
    "APIZACO": "APZ",
    "ATITALAQUIA": "ATI",
    "ATLACOMULCO": "ATL",
    "ACTOPAN": "ACT",
    "CANCUN 1": "CAN1",
    "CANCUN 2": "CAN2",
    "CEIBA": "CEI",
    "CELAYA": "CEL",
    "CHOLULA": "CHO",
    "CUAUTLA": "CUA",
    "GUADALAJARA": "GDL",
    "HUEJUTLA": "HUE",
    "IRAPUATO": "IRA",
    "IXMIQUILPAN": "IXM",
    "MERIDA": "MER",
    "MORELIA": "MOR",
    "MIXQUIAHUALA": "MIX",
    "OAXACA 1": "OAX1",
    "OAXACA 2": "OAX2",
    "PACHUCA 1": "PAC1",
    "PACHUCA 2": "PAC2",
    "PLAYA DEL CARMEN": "PDC",
    "PUEBLA 1": "PUE1",
    "PUEBLA 2": "PUE2",
    "PUEBLA 3": "PUE3",
    "PUEBLA 4": "PUE4",
    "QUERETARO 1": "QR01",
    "QUERETARO 2": "QR02",
    "QUERETARO 3": "QR03",
    "TEHUACAN": "TEH",
    "TEZIUTLAN": "TEZ",
    "TIZAYUCA": "TIZ",
    "TULANCINGO 1": "TUL1",
    "TULANCINGO 2": "TUL2",
    "VERACRUZ": "VER",
    "VILLAHERMOSA": "VHM",
    "ZUMPANGO 1": "ZUM1",
    "ZUMPANGO 2": "ZUM2",
    "CEDIS": "CEDIS",
    "CORPORATIVO": "CORP"
};

export const PRODUCT_CATEGORIES = [
    { id: "aro-amb", name: "Aromatizante Ambiental", image: "https://i.imgur.com/86dsPZV.jpeg" },
    { id: "antibac", name: "Antibacteriales", image: "https://i.imgur.com/RQfPreB.png" },
    { id: "bs-aro-amb", name: "Bases aromatizante ambiental", image: "https://i.imgur.com/lPo1L37.jpeg" },
    { id: "bs-lim-mult", name: "Bases limpiadores liquidos multiusos", image: "https://i.imgur.com/T99Fqdz.jpeg" },
    { id: "crem-corp", name: "Crema corporal", image: "https://i.imgur.com/NdvM2Zf.png" },
    { id: "det-trastes", name: "Detergente liquido para trastes", image: "https://i.imgur.com/gBct0aj.jpeg" },
    { id: "det-ropa", name: "Detergente líquido para ropa", image: "https://i.imgur.com/58v54Q6.jpeg" },
    { id: "enj-cap", name: "Enjuagues capilares", image: "https://i.imgur.com/EE3YF65.jpeg" },
    { id: "esp-hogar", name: "Especialidades cuidado del hogar", image: "https://i.imgur.com/RqcQxOB.jpeg" },
    { id: "esp-lavand", name: "Especialidades lavanderia", image: "https://i.imgur.com/ak01Ugq.png" },
    { id: "jab-manos", name: "Jabón liquido para manos", image: "https://i.imgur.com/WWHmKQ4.jpeg" },
    { id: "automotriz", name: "Línea automotriz", image: "https://i.imgur.com/zWXi9RD.png" },
    { id: "lim-mult", name: "Limpiador liquido multiusos", image: "https://i.imgur.com/f5SwpJ6.jpeg" },
    { id: "prod-interm", name: "Producto intermedio", image: "https://i.imgur.com/KjckUNn.jpeg" },
    { id: "refaro", name: "Reforzador de aromas(REFARO)", image: "https://i.imgur.com/MIJLRTO.png" },
    { id: "shampoo", name: "Shampoo capilar", image: "https://i.imgur.com/lbWy7oY.jpeg" },
    { id: "suavizante", name: "Suavizante de telas", image: "https://i.imgur.com/UrZoUPG.jpeg" },
    { id: "disoluciones", name: "Disoluciones de control", image: "https://i.imgur.com/RqcQxOB.jpeg" }
];

export const CATEGORY_PRODUCTS: Record<string, string[]> = {
    "Aromatizante Ambiental": ["AROANII", "AROCAN", "AROCAR", "AROCHIC", "AROCHIF", "ARODRA", "AROEST", "AROETE", "AROFER", "AROGAR", "AROHUG", "AROLUX", "ARONOR", "AROPOL"],
    "Antibacteriales": ["GELANT", "JABMAK", "LIMSAK", "SANBAK", "TRAGRA"],
    "Bases aromatizante ambiental": ["BAROANI", "BAROBRI", "BAROCAN", "BAROCAR", "BAROCHI", "BAROCHIF", "BARODRA", "BAROEST", "BAROETE", "BAROFER", "BAROGAR", "BAROHUG", "BAROLAV", "BAROLIM", "BAROLUX", "BAROMA2", "BAROMAC", "BAROMAN", "BAROMAR", "BAROMEN", "BAROMEX", "BARONOR", "BAROPEM", "BAROPOL", "BAROSTE", "BAROVIO"],
    "Bases limpiadores liquidos multiusos": ["BLIMALA", "BLIMANI", "BLIMBAB", "BLIMBOS", "BLIMBRI", "BLIMCAN", "BLIMCAR", "BLIMCAS", "BLIMCER", "BLIMCHI", "BLIMCHIC", "BLIMCOC", "BLIMDRAG", "BLIMEST", "BLIMETE", "BLIMFER", "BLIMFLO", "BLIMFRU", "BLIMGAR", "BLIMGPO", "BLIMHUG", "BLIMLAV", "BLIMLIM", "BLIMLIS", "BLIMLUX", "BLIMMAN", "BLIMMAND", "BLIMMANC", "BLIMMAR-1", "BLIMMAR-2", "BLIMMEN", "BLIMNAR", "BLIMNOR", "BLIMPER", "BLIMPOL", "BLIMPRI", "BLIMSTE", "BLIMVIO", "BPINBLA", "BPINCRI", "BPINVER"],
    "Crema corporal": ["CREBAB", "CREDEL", "CRELIM", "CREMIE", "CREROS", "CRESAB", "CREWHI"],
    "Detergente liquido para trastes": ["TRABLU", "TRALIM", "TRAMAN", "TRANAR", "TRATOR", "XPUMAX"],
    "Detergente líquido para ropa": ["AQUA", "COLBLA", "COLGIN", "COLNEG", "DETDON", "ENCANTO", "GIRIEL", "GIRIEL2", "GIRIELOXI", "GIRDOW", "PERGIN", "PERLA", "SHAGIN", "SUNSET", "VELGIN", "VIVGIN", "ZOTAZU", "ZOTBLA", "ZOTROS"],
    "Enjuagues capilares": ["ENJROS", "ENJDUR", "ENJHIE"],
    "Especialidades cuidado del hogar": ["ACEROJ", "CLO", "CLOGEL", "DETAMO", "DETER", "INS", "LIMREP", "LIMVID", "MOP", "QUILIQ", "QUIPAS", "QUISAR", "SARRIGEL", "SHAMAS", "TEFESP", "TEFLIQ"],
    "Especialidades lavanderia": ["DES", "DETNEU", "DETPIN", "GINESH", "PLAPLUS", "PLAFAC"],
    "Jabón liquido para manos": ["JABCER", "JABCOC", "JABDUR", "JABHIE", "JABNEU", "JABPM", "JABPRI", "JABUVA"],
    "Línea automotriz": ["ALTBRI", "BRIGEL", "BRILIQ", "CERLIQ", "CREMEC", "DESIND", "DESMOT", "GINESP", "GINLIQ", "SHACER", "SHACLA"],
    "Limpiador liquido multiusos": ["LIMALA", "LIMBOS", "LIMBRI", "LIMCAN", "LIMCAS", "LIMCHI", "LIMFRU", "LIMLAV", "LIMLIM", "LIMLIS", "LIMMANC", "LIMMAND", "LIMMAR", "LIMMEN", "LIMPERM", "LIMPOET", "LIMPRI", "LIMSTE", "LIMVIO", "PINBLA", "PINO", "PINVER"],
    "Producto intermedio": ["DETALC", "EMU", "FFLO", "BSUA", "RAOI"],
    "Reforzador de aromas(REFARO)": ["REFARO-SUE", "REFARO-LIB", "REFARO-MAG", "REFARO-INT", "REFARO-NAT", "REFARO-LUN", "REFARO-BLUE", "REFARO-EDE", "REFARO-PAS", "REFARO-SEN", "REFARO-PRI", "REFARO-BAB", "REFARO-DEL"],
    "Shampoo capilar": ["SHAPAN", "SHAHEA", "SHADUR", "SHAPLU", "SHAHIE"],
    "Suavizante de telas": ["SUASUE", "SUALIB", "SUAMAG", "SUAINT", "SUANAT", "SUALUN", "SUABLU", "SUAPAS", "SUASEN", "SUAPRI", "SUABAB", "SUADEL", "SUANEU"],
    "Disoluciones de control": ["CITGIN", "SOSA10", "ESP25", "LNG5"]
};

export const PRODUCT_STANDARDS: Record<string, { min?: number, max?: number }> = {
    "LIMLIM": { min: 1.0, max: 2.0 },
    "LIMVIO": { min: 1.0, max: 1.9 },
    "LIMMAR": { min: 1.0, max: 1.9 },
    "LIMCAS": { min: 1.1, max: 2.0 },
    "LIMBRI": { min: 1.1, max: 2.0 },
    "LIMCAN": { min: 1.5, max: 2.3 },
    "LIMCHI": { min: 1.1, max: 2.3 },
    "LIMBOS": { min: 1.1, max: 2.2 },
    "LIMLAV": { min: 0.8, max: 1.6 },
    "LIMPERM": { min: 1.2, max: 2.0 },
    "LIMMEN": { min: 1.0, max: 1.9 },
    "LIMSTE": { min: 1.0, max: 2.0 },
    "LIMFRU": { min: 1.1, max: 2.0 },
    "LIMPOET": { min: 1.1, max: 2.1 },
    "LIMMANC": { min: 1.5, max: 2.5 },
    "LIMLIS": { min: 1.0, max: 1.6 },
    "LIMALA": { min: 1.1, max: 2.2 },
    "TRALIM": { min: 15.0, max: 17.5 },
    "TRAMAN": { min: 15.0, max: 17.5 },
    "TRANAR": { min: 15.0, max: 17.5 },
    "TRATOR": { min: 14.5, max: 17.0 },
    "XPUMAX": { min: 15.0, max: 17.5 },
    "CLOGEL": { min: 6.2, max: 8.5 },
    "CLO": { min: 6.0, max: 8.0 },
    "PINO": { min: 3.5, max: 4.5 },
    "DETNEU": { min: 10.5, max: 12.5 },
    "INS": { min: 1.5, max: 2.5 },
    "DETER": { min: 16.0, max: 18.0 },
    "LIMREP": { min: 4.0, max: 5.5 },
    "LIMVID": { min: 1.0, max: 1.9 },
    "DETAMO": { min: 12.5, max: 14.0 },
    "DESIND": { min: 23.0, max: 26.0 },
    "TEFLIQ": { min: 10.0, max: 11.5 },
    "TEFESP": { min: 17.0, max: 19.5 },
    "SHAMAS": { min: 8.0, max: 9.7 },
    "QUILIQ": { min: 12.0, max: 14.5 },
    "COLGIN": { min: 9.0, max: 10.5 },
    "COLBLA": { min: 9.0, max: 10.5 },
    "COLNEG": { min: 9.0, max: 10.5 },
    "GIRIEL": { min: 9.0, max: 10.5 },
    "GIRIEL2": { min: 9.0, max: 10.5 },
    "GIRDOW": { min: 9.0, max: 10.5 },
    "PERGIN": { min: 9.0, max: 10.5 },
    "VIVGIN": { min: 8.5, max: 10.5 },
    "GIRIELOXI": { min: 8.5, max: 10.5 },
    "SUNSET": { min: 8.5, max: 10.5 },
    "SHAGIN": { min: 8.5, max: 10.5 },
    "ZOTROS": { min: 10.0, max: 14.5 },
    "ZOTBLA": { min: 10.0, max: 14.5 },
    "ZOTAZU": { min: 10.0, max: 14.5 },
    "AQUA": { min: 10.5, max: 13.5 },
    "DETDON": { min: 10.5, max: 13.5 },
    "PERLA": { min: 10.0, max: 13.5 },
    "ENCANTO": { min: 10.0, max: 13.5 },
    "VELGIN": { min: 8.0, max: 11.0 },
    "SUASUE": { min: 1.1, max: 2.3 },
    "SUALIB": { min: 1.3, max: 2.6 },
    "SUAMAG": { min: 1.2, max: 3.2 },
    "SUAINT": { min: 1.5, max: 2.9 },
    "SUANAT": { min: 1.3, max: 2.5 },
    "SUALUN": { min: 1.7, max: 2.7 },
    "SUABLU": { min: 1.5, max: 2.4 },
    "SUAPAS": { min: 1.0, max: 2.2 },
    "SUASEN": { min: 1.0, max: 2.4 },
    "SUAPRI": { min: 1.6, max: 2.6 },
    "SUABAB": { min: 1.1, max: 2.2 },
    "SUADEL": { min: 1.1, max: 2.7 },
    "DES": { min: 14.5, max: 16.5 },
    "DETPIN": { min: 8.7, max: 9.9 },
    "GINESH": { min: 5.0, max: 6.2 },
    "SHACER": { min: 8.5, max: 9.5 },
    "SHACLA": { min: 12.0, max: 13.5 },
    "ALTBRI": { min: 38.0, max: 38.6 },
    "BRILIQ": { min: 18.5, max: 20.5 },
    "BRIGEL": { min: 21.5, max: 24.5 },
    "GINLIQ": { min: 10.5, max: 11.5 },
    "DESMOT": { min: 21.0, max: 23.5 },
    "CERLIQ": { min: 7.5, max: 9.0 },
    "CREMEC": { min: 37.0, max: 40.5 },
    "GELANT": { min: 19.5, max: 23.5 },
    "SANBAK": { min: 1.0, max: 1.5 },
    "LIMSAK": { min: 1.5, max: 2.0 },
    "JABMAK": { min: 12.0, max: 13.5 },
    "TRAGRA": { min: 20.0, max: 22.5 },
    "JABPM": { min: 10.5, max: 14.0 },
    "JABNEU": { min: 9.0, max: 10.5 },
    "JABCER": { min: 10.5, max: 14.0 },
    "JABUVA": { min: 10.5, max: 14.0 },
    "JABHIE": { min: 10.5, max: 14.0 },
    "JABCOC": { min: 10.0, max: 14.0 },
    "SHAPAN": { min: 7.5, max: 9.5 },
    "SHAHEA": { min: 7.5, max: 9.5 },
    "ENJROS": { min: 1.5, max: 2.5 },
    "DETALC": { min: 15.5, max: 18.5 },
    "CITGIN": { min: 20.0, max: 25.0 },
    "SOSA10": { min: 8.0, max: 12.0 },
    "ESP25": { min: 25.0, max: 30.0 },
    // Detergentes de trastes
    "TRABLU": { min: 14.5, max: 17.0 },
    // Suavizantes
    "SUANEU": { min: 1.1, max: 2.4 },
    // Cremas (usar rangos de CREDEL)
    "CREBAB": { min: 18.0, max: 22.0 },
    "CRELIM": { min: 18.0, max: 22.0 },
    "CREMIE": { min: 18.0, max: 22.0 },
    "CREROS": { min: 18.0, max: 22.0 },
    "CRESAB": { min: 18.0, max: 22.0 },
    "CREWHI": { min: 18.0, max: 22.0 },
    // Enjuagues
    "ENJDUR": { min: 1.1, max: 2.4 },
    "ENJHIE": { min: 1.1, max: 2.4 },
    // Shampoos (usar rangos similares a SHAPAN/SHAHEA)
    "SHADUR": { min: 7.5, max: 9.5 },
    "SHAPLU": { min: 7.5, max: 9.5 },
    "SHAHIE": { min: 7.5, max: 9.5 },
    // Jabones de manos (usar rango similar a JABPM/JABNEU)
    "JABDUR": { min: 10.5, max: 14.0 }
};

export const PH_STANDARDS: Record<string, { min: number, max: number }> = {
    "TRALIM": { min: 8, max: 8 }, "TRAMAN": { min: 8, max: 8 }, "TRANAR": { min: 8, max: 8 }, "TRATOR": { min: 8, max: 8 }, "XPUMAX": { min: 8, max: 8 },
    "CLOGEL": { min: 12, max: 14 }, "QUIPAS": { min: 12, max: 14 }, "DETNEU": { min: 7, max: 7 }, "DETAMO": { min: 9, max: 13 }, "QUILIQ": { min: 8, max: 8 }, "DETER": { min: 2, max: 4 },
    "TEFESP": { min: 7, max: 7 }, "SHAMAS": { min: 7, max: 7 },
    "COLGIN": { min: 7, max: 9 }, "COLBLA": { min: 7, max: 9 }, "COLNEG": { min: 7, max: 9 }, "GIRIEL": { min: 7, max: 9 }, "GIRIEL2": { min: 7, max: 9 }, "GIRDOW": { min: 7, max: 9 },
    "PERGIN": { min: 7, max: 9 }, "VIVGIN": { min: 7, max: 9 }, "GIRIELOXI": { min: 7, max: 9 }, "SUNSET": { min: 7, max: 9 }, "SHAGIN": { min: 7, max: 9 },
    "ZOTROS": { min: 7, max: 9 }, "ZOTBLA": { min: 7, max: 9 }, "ZOTAZU": { min: 7, max: 9 }, "AQUA": { min: 7, max: 9 }, "DETDON": { min: 7, max: 9 },
    "PERLA": { min: 7, max: 9 }, "ENCANTO": { min: 7, max: 9 }, "VELGIN": { min: 7, max: 7 },
    "DES": { min: 9, max: 9 }, "DETPIN": { min: 7, max: 9 }, "GINESH": { min: 3, max: 4 },
    "SHACER": { min: 6, max: 7 }, "SHACLA": { min: 6, max: 7 }, "BRIGEL": { min: 6, max: 7 }, "GINESP": { min: 6, max: 7 }, "BRILIQ": { min: 7, max: 7 }, "CREMEC": { min: 7, max: 7 },
    "GELANT": { min: 6, max: 7 }, "JABMAK": { min: 6, max: 7 }, "TRAGRA": { min: 7, max: 9 },
    "JABPM": { min: 5, max: 6 }, "JABNEU": { min: 7, max: 7 }, "JABCER": { min: 5, max: 6 }, "JABUVA": { min: 5, max: 6 }, "JABHIE": { min: 5, max: 6 }, "JABCOC": { min: 5, max: 6 }, "JABDUR": { min: 5, max: 6 },
    "SHAPAN": { min: 6, max: 7 }, "SHAHEA": { min: 6, max: 7 }, "CREDEL": { min: 6, max: 7 },
    // Cremas (usar rangos de CREDEL)
    "CREBAB": { min: 6, max: 7 }, "CRELIM": { min: 6, max: 7 }, "CREMIE": { min: 6, max: 7 }, "CREROS": { min: 6, max: 7 }, "CRESAB": { min: 6, max: 7 }, "CREWHI": { min: 6, max: 7 },
    // Shampoos (usar rangos similares a SHAPAN/SHAHEA)
    "SHADUR": { min: 6, max: 7 }, "SHAPLU": { min: 6, max: 7 }, "SHAHIE": { min: 6, max: 7 },
    // Detergentes de trastes
    "TRABLU": { min: 8, max: 8 },
    "DETALC": { min: 7, max: 10 },
};

export const APPEARANCE_STANDARDS: Record<string, string> = {
    // === AROMATIZANTES ===
    "AROANII": "OPACO",
    "AROCAN": "OPACO",
    "AROCAR": "OPACO",
    "AROCHIC": "OPACO",
    "AROCHIF": "OPACO",
    "ARODRA": "OPACO",
    "AROEST": "OPACO",
    "AROETE": "OPACO",
    "AROFER": "OPACO",
    "AROGAR": "OPACO",
    "AROHUG": "OPACO",
    "AROLUX": "OPACO",
    "ARONOR": "OPACO",
    "AROPOL": "OPACO",

    // === BASES PARA AROMATIZANTES AMBIENTALES ===
    "BAROANI": "OPACO",
    "BAROBRI": "OPACO",
    "BAROCAN": "OPACO",
    "BAROCAR": "OPACO",
    "BAROCHI": "OPACO",
    "BAROCHIF": "OPACO",
    "BARODRA": "OPACO",
    "BAROEST": "OPACO",
    "BAROETE": "OPACO",
    "BAROFER": "OPACO",
    "BAROGAR": "OPACO",
    "BAROHUG": "OPACO",
    "BAROLAV": "OPACO",
    "BAROLIM": "OPACO",
    "BAROLUX": "OPACO",
    "BAROMA2": "OPACO",
    "BAROMAC": "OPACO",
    "BAROMAN": "OPACO",
    "BAROMAR": "OPACO",
    "BAROMEN": "OPACO",
    "BAROMEX": "OPACO",
    "BARONOR": "OPACO",
    "BAROPEM": "OPACO",
    "BAROPOL": "OPACO",
    "BAROSTE": "OPACO",
    "BAROVIO": "OPACO",

    // === LIMPIADORES LÍQUIDOS MULTIUSOS ===
    "LIMLIM": "CRISTALINO",
    "LIMVIO": "CRISTALINO",
    "LIMMAR": "CRISTALINO",
    "LIMCAS": "CRISTALINO",
    "LIMBRI": "CRISTALINO",
    "LIMCAN": "CRISTALINO",
    "LIMCHI": "CRISTALINO",
    "LIMBOS": "CRISTALINO",
    "LIMLAV": "CRISTALINO",
    "LIMPERM": "CRISTALINO",
    "LIMMEN": "CRISTALINO",
    "LIMSTE": "CRISTALINO",
    "LIMFRU": "CRISTALINO",
    "LIMPOET": "CRISTALINO",
    "LIMMANC": "CRISTALINO",
    "LIMLIS": "CRISTALINO",
    "LIMALA": "CRISTALINO",
    "PINO": "CRISTALINO",
    "PINBLA": "OPACO",
    "PINVER": "OPACO",

    // === BASES LIMPIADORES LÍQUIDOS MULTIUSOS ===
    "BLIMALA": "OPACO",
    "BLIMANI": "OPACO",
    "BLIMBAB": "OPACO",
    "BLIMBOS": "OPACO",
    "BLIMBRI": "OPACO",
    "BLIMCAN": "OPACO",
    "BLIMCAR": "OPACO",
    "BLIMCAS": "OPACO",
    "BLIMCER": "OPACO",
    "BLIMCHI": "OPACO",
    "BLIMCHIC": "OPACO",
    "BLIMCOC": "OPACO",
    "BLIMDRAG": "OPACO",
    "BLIMEST": "OPACO",
    "BLIMETE": "OPACO",
    "BLIMFER": "OPACO",
    "BLIMFLO": "OPACO",
    "BLIMFRU": "OPACO",
    "BLIMGAR": "OPACO",
    "BLIMGPO": "OPACO",
    "BLIMHUG": "OPACO",
    "BLIMLAV": "OPACO",
    "BLIMLIM": "OPACO",
    "BLIMLIS": "OPACO",
    "BLIMLUX": "OPACO",
    "BLIMMAN": "OPACO",
    "BLIMMAND": "OPACO",
    "BLIMMANC": "OPACO",
    "BLIMMAR-1": "OPACO",
    "BLIMMAR-2": "OPACO",
    "BLIMMEN": "OPACO",
    "BLIMNAR": "OPACO",
    "BLIMNOR": "OPACO",
    "BLIMPER": "OPACO",
    "BLIMPOL": "OPACO",
    "BLIMPRI": "OPACO",
    "BLIMSTE": "OPACO",
    "BLIMVIO": "OPACO",
    "BPINBLA": "OPACO",
    "BPINCRI": "OPACO",
    "BPINVER": "OPACO",

    // === DETERGENTES LÍQUIDOS PARA TRASTES ===
    "TRALIM": "CRISTALINO",
    "TRAMAN": "CRISTALINO",
    "TRANAR": "CRISTALINO",
    "TRATOR": "CRISTALINO",
    "TRABLU": "CRISTALINO",
    "XPUMAX": "CRISTALINO",

    // === ESPECIALIDADES CUIDADO DEL HOGAR ===
    "CLOGEL": "CRISTALINO",
    "CLO": "CRISTALINO",
    "QUIPAS": "OPACO",
    "DETNEU": "CRISTALINO",
    "INS": "OPACO",
    "DETER": "CRISTALINO",
    "LIMVID": "CRISTALINO",
    "DETAMO": "CRISTALINO",
    "TEFLIQ": "OPACO",
    "TESESP": "OPACO",
    "SHAMAS": "APERLADO",
    "ACEROJ": "CRISTALINO",
    "LIMREP": "CRISTALINO",
    "MOP": "CRISTALINO",
    "QUILIQ": "CRISTALINO",
    "QUISAR": "CRISTALINO",
    "SARRIGEL": "OPACO",


    // === LAVANDERÍA: DETERGENTES LÍQUIDOS PARA ROPA ===
    "COLGIN": "CRISTALINO", "COLBLA": "CRISTALINO", "COLNEG": "CRISTALINO", "GIRIEL": "CRISTALINO", "GIRIEL2": "CRISTALINO", "GIRDOW": "CRISTALINO",
    "PERGIN": "CRISTALINO",
    "VIVGIN": "CRISTALINO",
    "GIRIELOXI": "APERLADO",
    "SUNSET": "APERLADO",
    "SHAGIN": "APERLADO",
    "ZOTROS": "OPACO",
    "ZOTBLA": "OPACO",
    "ZOTAZU": "OPACO",
    "AQUA": "CRISTALINO",
    "DETDON": "CRISTALINO",
    "PERLA": "APERLADO",
    "ENCANTO": "APERLADO",
    "VELGIN": "APERLADO",

    // === SUAVIZANTES DE TELAS ===
    "SUASUE": "OPACO",
    "SUALIB": "OPACO",
    "SUAMAG": "OPACO",
    "SUAINT": "OPACO",
    "SUANAT": "OPACO",
    "SUALUN": "OPACO",
    "SUABLU": "OPACO",
    "SUAPAS": "OPACO",
    "SUASEN": "OPACO",
    "SUAPRI": "OPACO",
    "SUABAB": "OPACO",
    "SUADEL": "OPACO",
    "SUANEU": "OPACO",

    // === ESPECIALIDADES LAVANDERÍA ===
    "DES": "CRISTALINO",
    "DETPIN": "APERLADO",
    "GINESH": "CRISTALINO",
    "PLAFAC": "OPACO",
    "PLAPLUS": "OPACO",

    // === LÍNEA AUTOMOTRIZ ===
    "SHACER": "OPACO",
    "SHACLA": "CRISTALINO",
    "ALTBRI": "CRISTALINO",
    "BRILIQ": "CRISTALINO",
    "BRIGEL": "CRISTALINO",
    "GINLIQ": "OPACO",
    "GINESP": "OPACO",
    "DESMOT": "CRISTALINO",
    "CERLIQ": "OPACO",
    "CREMEC": "CRISTALINO",
    "DESIND": "CRISTALINO",

    // === LÍNEA ANTIBACTERIALES ===
    "GELANT": "CRISTALINO",
    "SANBAK": "CRISTALINO",
    "LIMSAK": "CRISTALINO",
    "JABMAK": "CRISTALINO",
    "TRAGRA": "CRISTALINO",

    // === LÍNEA CUIDADO PERSONAL ===
    "JABPM": "CRISTALINO",
    "JABNEU": "CRISTALINO",
    "JABCER": "CRISTALINO",
    "JABUVA": "CRISTALINO",
    "JABHIE": "CRISTALINO",
    "JABCOC": "APERLADO",
    "JABDUR": "CRISTALINO",

    "SHAPAN": "APERLADO",
    "SHAHEA": "APERLADO",
    "SHADUR": "APERLADO",
    "SHAPLU": "APERLADO",
    "SHAHIE": "APERLADO",

    "ENJROS": "OPACO",
    "ENJDUR": "OPACO",
    "ENJHIE": "OPACO",

    "CREDEL": "OPACO",
    "CREBAB": "OPACO",
    "CRELIM": "OPACO",
    "CREMIE": "OPACO",
    "CREROS": "OPACO",
    "CRESAB": "OPACO",
    "CREWHI": "OPACO",

    //=== REFORZADORES DE AROMA==
    "REFARO-SUE": "OPACO",
    "REFARO-LIB": "OPACO",
    "REFARO-MAG": "OPACO",
    "REFARO-INT": "OPACO",
    "REFARO-NAT": "OPACO",
    "REFARO-LUN": "OPACO",
    "REFARO-BLUE": "OPACO",
    "REFARO-EDE": "OPACO",
    "REFARO-PAS": "OPACO",
    "REFARO-SEN": "OPACO",
    "REFARO-PRI": "OPACO",
    "REFARO-BAB": "OPACO",
    "REFARO-DEL": "OPACO",

    // === PRODUCTOS INTERMEDIOS ===
    "DETALC": "CRISTALINO",
    "EMU": "CRISTALINO",
    "FFLO": "CRISTALINO",
    "BSUA": "OPACO",
    "RAOI": "CRISTALINO",


    // === DISOLUCIONES INTERMEDIOS ===
    "CITGIN": "CRISTALINO",
    "SOSA10": "CRISTALINO",
    "ESP25": "CRISTALINO",
    "LNG5": "OPACO"
};

export const PARAMETER_APPLICABILITY: Record<string, { solidos: boolean, ph: boolean }> = {
    "AROANII": { solidos: false, ph: false }, "AROCAN": { solidos: false, ph: false }, "AROCAR": { solidos: false, ph: false }, "AROCHIC": { solidos: false, ph: false }, "AROCHIF": { solidos: false, ph: false }, "ARODRA": { solidos: false, ph: false }, "AROEST": { solidos: false, ph: false }, "AROETE": { solidos: false, ph: false }, "AROFER": { solidos: false, ph: false }, "AROGAR": { solidos: false, ph: false }, "AROHUG": { solidos: false, ph: false }, "AROLUX": { solidos: false, ph: false }, "ARONOR": { solidos: false, ph: false }, "AROPOL": { solidos: false, ph: false },
    "BAROANI": { solidos: false, ph: false }, "BAROBRI": { solidos: false, ph: false }, "BAROCAN": { solidos: false, ph: false }, "BAROCAR": { solidos: false, ph: false }, "BAROCHI": { solidos: false, ph: false }, "BAROCHIF": { solidos: false, ph: false }, "BARODRA": { solidos: false, ph: false }, "BAROEST": { solidos: false, ph: false }, "BAROETE": { solidos: false, ph: false }, "BAROFER": { solidos: false, ph: false }, "BAROGAR": { solidos: false, ph: false }, "BAROHUG": { solidos: false, ph: false }, "BAROLAV": { solidos: false, ph: false }, "BAROLIM": { solidos: false, ph: false }, "BAROLUX": { solidos: false, ph: false }, "BAROMA2": { solidos: false, ph: false }, "BAROMAC": { solidos: false, ph: false }, "BAROMAN": { solidos: false, ph: false }, "BAROMAR": { solidos: false, ph: false }, "BAROMEN": { solidos: false, ph: false }, "BAROMEX": { solidos: false, ph: false }, "BARONOR": { solidos: false, ph: false }, "BAROPEM": { solidos: false, ph: false }, "BAROPOL": { solidos: false, ph: false }, "BAROSTE": { solidos: false, ph: false }, "BAROVIO": { solidos: false, ph: false },
    "LIMLIM": { solidos: true, ph: false }, "LIMVIO": { solidos: true, ph: false }, "LIMMAR": { solidos: true, ph: false }, "LIMCAS": { solidos: true, ph: false }, "LIMBRI": { solidos: true, ph: false }, "LIMCAN": { solidos: true, ph: false }, "LIMCHI": { solidos: true, ph: false }, "LIMBOS": { solidos: true, ph: false }, "LIMLAV": { solidos: true, ph: false }, "LIMPERM": { solidos: true, ph: false }, "LIMMEN": { solidos: true, ph: false }, "LIMSTE": { solidos: true, ph: false }, "LIMFRU": { solidos: true, ph: false }, "LIMPOET": { solidos: true, ph: false }, "LIMMANC": { solidos: true, ph: false }, "LIMLIS": { solidos: true, ph: false }, "LIMALA": { solidos: true, ph: false }, "PINO": { solidos: true, ph: false }, "PINBLA": { solidos: false, ph: false }, "PINVER": { solidos: false, ph: false },
    "TRALIM": { solidos: true, ph: true }, "TRAMAN": { solidos: true, ph: true }, "TRANAR": { solidos: true, ph: true }, "TRATOR": { solidos: true, ph: true }, "TRABLU": { solidos: true, ph: true }, "XPUMAX": { solidos: true, ph: true },
    "CLOGEL": { solidos: true, ph: true }, "CLO": { solidos: true, ph: false }, "QUIPAS": { solidos: false, ph: false }, "DETNEU": { solidos: true, ph: true }, "INS": { solidos: true, ph: false }, "DETER": { solidos: true, ph: true }, "LIMVID": { solidos: true, ph: false }, "DETAMO": { solidos: true, ph: true }, "TEFLIQ": { solidos: true, ph: false }, "TEFESP": { solidos: true, ph: true }, "SHAMAS": { solidos: true, ph: true }, "ACEROJ": { solidos: false, ph: false }, "LIMREP": { solidos: true, ph: false }, "MOP": { solidos: false, ph: false }, "QUILIQ": { solidos: true, ph: true }, "QUISAR": { solidos: false, ph: false }, "SARRIGEL": { solidos: false, ph: false },
    "COLGIN": { solidos: true, ph: true }, "COLBLA": { solidos: true, ph: true }, "COLNEG": { solidos: true, ph: true }, "GIRIEL": { solidos: true, ph: true }, "GIRIEL2": { solidos: true, ph: true }, "GIRDOW": { solidos: true, ph: true }, "PERGIN": { solidos: true, ph: true }, "VIVGIN": { solidos: true, ph: true }, "GIRIELOXI": { solidos: true, ph: true }, "SUNSET": { solidos: true, ph: true }, "SHAGIN": { solidos: true, ph: true }, "ZOTROS": { solidos: true, ph: true }, "ZOTBLA": { solidos: true, ph: true }, "ZOTAZU": { solidos: true, ph: true }, "AQUA": { solidos: true, ph: true }, "DETDON": { solidos: true, ph: true }, "PERLA": { solidos: true, ph: true }, "ENCANTO": { solidos: true, ph: true }, "VELGIN": { solidos: true, ph: true },
    "SUASUE": { solidos: true, ph: false }, "SUALIB": { solidos: true, ph: false }, "SUAMAG": { solidos: true, ph: false }, "SUAINT": { solidos: true, ph: false }, "SUANAT": { solidos: true, ph: false }, "SUALUN": { solidos: true, ph: false }, "SUABLU": { solidos: true, ph: false }, "SUAPAS": { solidos: true, ph: false }, "SUASEN": { solidos: true, ph: false }, "SUAPRI": { solidos: true, ph: false }, "SUABAB": { solidos: true, ph: false }, "SUADEL": { solidos: true, ph: false }, "SUANEU": { solidos: true, ph: false },
    "DES": { solidos: true, ph: true }, "DETPIN": { solidos: true, ph: true }, "GINESH": { solidos: true, ph: true }, "PLAFAC": { solidos: false, ph: false }, "PLAPLUS": { solidos: false, ph: false },
    "SHACER": { solidos: true, ph: true }, "SHACLA": { solidos: true, ph: true }, "ALTBRI": { solidos: true, ph: false }, "BRILIQ": { solidos: true, ph: true }, "BRIGEL": { solidos: true, ph: true }, "GINLIQ": { solidos: true, ph: false }, "GINESP": { solidos: false, ph: true }, "DESMOT": { solidos: true, ph: false }, "CERLIQ": { solidos: true, ph: false }, "CREMEC": { solidos: true, ph: true }, "DESIND": { solidos: true, ph: false },
    "GELANT": { solidos: true, ph: true }, "SANBAK": { solidos: true, ph: false }, "LIMSAK": { solidos: true, ph: false }, "JABMAK": { solidos: true, ph: true }, "TRAGRA": { solidos: true, ph: true },
    "JABPM": { solidos: true, ph: true }, "JABNEU": { solidos: true, ph: true }, "JABCER": { solidos: true, ph: true }, "JABUVA": { solidos: true, ph: true }, "JABHIE": { solidos: true, ph: true }, "JABCOC": { solidos: true, ph: true }, "JABDUR": { solidos: true, ph: true },
    "SHAPAN": { solidos: true, ph: true }, "SHAHEA": { solidos: true, ph: true }, "SHADUR": { solidos: true, ph: true }, "SHAPLU": { solidos: true, ph: true }, "SHAHIE": { solidos: true, ph: true },
    "ENJROS": { solidos: true, ph: false }, "ENJDUR": { solidos: true, ph: false }, "ENJHIE": { solidos: true, ph: false },
    "CREDEL": { solidos: false, ph: true }, "CREBAB": { solidos: true, ph: true }, "CRELIM": { solidos: true, ph: true }, "CREMIE": { solidos: true, ph: true }, "CREROS": { solidos: true, ph: true }, "CRESAB": { solidos: true, ph: true }, "CREWHI": { solidos: true, ph: true },
    "REFARO-SUE": { solidos: false, ph: false }, "REFARO-LIB": { solidos: false, ph: false }, "REFARO-MAG": { solidos: false, ph: false }, "REFARO-INT": { solidos: false, ph: false }, "REFARO-NAT": { solidos: false, ph: false }, "REFARO-LUN": { solidos: false, ph: false }, "REFARO-BLUE": { solidos: false, ph: false }, "REFARO-EDE": { solidos: false, ph: false }, "REFARO-PAS": { solidos: false, ph: false }, "REFARO-SEN": { solidos: false, ph: false }, "REFARO-PRI": { solidos: false, ph: false }, "REFARO-BAB": { solidos: false, ph: false }, "REFARO-DEL": { solidos: false, ph: false },
    "DETALC": { solidos: true, ph: true }, "EMU": { solidos: false, ph: false }, "FFLO": { solidos: false, ph: false }, "BSUA": { solidos: false, ph: false }, "RAOI": { solidos: false, ph: false },
    "CITGIN": { solidos: true, ph: false }, "SOSA10": { solidos: true, ph: false }, "ESP25": { solidos: true, ph: false }, "LNG5": { solidos: false, ph: false }
};

export const PRODUCT_GROUPS = [
    {
        title: "Cuidado del Hogar",
        color: "text-orange-600 dark:text-orange-400",
        icon: "🏠",
        ids: ["aro-amb", "esp-hogar", "lim-mult", "det-trastes", "bs-aro-amb", "bs-lim-mult"]
    },
    {
        title: "Cuidado Personal",
        color: "text-emerald-600 dark:text-emerald-400",
        icon: "💆",
        ids: ["crem-corp", "enj-cap", "jab-manos", "shampoo"]
    },
    {
        title: "Lavandería",
        color: "text-blue-600 dark:text-blue-400",
        icon: "🧺",
        ids: ["det-ropa", "suavizante", "esp-lavand", "refaro"]
    },
    {
        title: "Línea Automotriz",
        color: "text-slate-600 dark:text-slate-400",
        icon: "🚗",
        ids: ["automotriz"]
    },
    {
        title: "Línea Antibacterial",
        color: "text-cyan-600 dark:text-cyan-400",
        icon: "🛡️",
        ids: ["antibac"]
    },
    {
        title: "Productos Intermedios",
        color: "text-indigo-600 dark:text-indigo-400",
        icon: "🏭",
        ids: ["prod-interm", "disoluciones"]
    }
];
